version: "3"

services:
  # MongoDB Database
  #mongodb:
   # image: mongo
    #container_name: mongodb
    #ports:
    #  - "27017:27017"
    #volumes:
     # - mongo_data:/data/db
    #networks:
     # - nightscout_net
    #restart: always

  # FastAPI app
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-app
    #ports:
    #  - "8000:8000"
    environment:
      - MONGO_URI=mongodb://app_user:Fantokh1990@20.246.81.129:27017/main_db?authSource=admin
    #depends_on:
    #  - mongodb
    env_file:
      - ./backend/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nightscout_net
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`nst1d.com`)"
      - "traefik.http.routers.fastapi.entrypoints=web"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8000"

  # Traefik Proxy
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      #- "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      #- "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - nightscout_net
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - nightscout_net
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cadvisor.rule=Host(`cadvisor.nst1d.com`)"
      - "traefik.http.routers.cadvisor.entrypoints=web"
      - "traefik.http.services.cadvisor.loadbalancer.server.port=8080"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - nightscout_net
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.nst1d.com`)"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - nightscout_net
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.nst1d.com`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"


networks:
  nightscout_net:
    driver: bridge

volumes:
  #mongo_data:
  grafana-storage:
