entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true  # يسمح باستخدام X-Forwarded-Proto

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

api:
  dashboard: false
